CREATE DATABASE AMARRAMA ;
CREATE TABLE Employee(
 ID INT PRIMARY KEY,
 NAME VARCHAR (50),
 Salary INT
 );
INSERT INTO Employee VALUES(1,"AMAR",50000);
INSERT INTO Employee
(ID , NAME , Salary)
VALUES 
(2, "NATH",30400),
(3, "KOLLA",45000);
SELECT *FROM Employee;
SHOW TABLES;

